### ISSUE TITLE
Issue 1: Set up PostgreSQL with Prisma as the ORM

### ISSUE THREAD

**Issue by ricky-ultimate** [ricky-ultimate/stemdb#1]
### Task: Set up PostgreSQL with Prisma as the ORM

- [x] Install Prisma and initialize it
- [x] Define Prisma models
- [x] Configure PostgreSQL connection
- [x] Run migrations

Part of [#4 ](https://github.com/ricky-ultimate/stemdb/issues/4)
