### ISSUE TITLE
Issue 2: Create API routes for CRUD operations

### ISSUE THREAD

**Issue by ricky-ultimate** [ricky-ultimate/stemdb#2]
### Task: Create API routes for CRUD operations

- [x] Create API route for creating a member
  - [x] Implement POST handler to add a new member
- [x] Create API route for reading members
  - [x] Implement GET handler to retrieve all members
  - [x] Implement GET handler to retrieve a single member by ID
- [x] Create API route for updating a member
  - [x] Implement PUT/PATCH handler to update member details
- [x] Create API route for deleting a member
  - [x] Implement DELETE handler to remove a member
- [x] Repeat the above steps for projects
  - [x] Implement POST handler to add a new project
  - [x] Implement GET handler to retrieve all projects
  - [x] Implement GET handler to retrieve a single project by ID
  - [x] Implement PUT/PATCH handler to update project details
  - [x] Implement DELETE handler to remove a project
- [x] Repeat the above steps for events
  - [x] Implement POST handler to add a new event
  - [x] Implement GET handler to retrieve all events
  - [x] Implement GET handler to retrieve a single event by ID
  - [x] Implement PUT/PATCH handler to update event details
  - [x] Implement DELETE handler to remove an event

Part of [#4 ](https://github.com/ricky-ultimate/stemdb/issues/4)
