### ISSUE TITLE
Master Issue: STEM Community Web Application Development

### ISSUE THREAD

**Issue by ricky-ultimate** [ricky-ultimate/stemdb#4]
# Master Issue: STEM Community Web Application Development

This master issue tracks the primary tasks required to develop the STEM Community web application.

## Primary Tasks

- [x] [Set up PostgreSQL with Prisma as the ORM](https://github.com/ricky-ultimate/stemdb/issues/1)
- [x] [Create API routes for CRUD operations](https://github.com/ricky-ultimate/stemdb/issues/2)
- [ ] [Create the front-end components and pages for members, projects, and events](https://github.com/ricky-ultimate/stemdb/issues/3)
